# Generated by Django 5.0.6 on 2024-05-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('moviename', models.CharField(max_length=100)),
                ('heroname', models.CharField(max_length=100)),
            ],
        ),
    ]
