# Generated by Django 5.0.6 on 2024-05-31 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Names',
            new_name='MovieDetaisl',
        ),
    ]
