# Generated by Django 5.0.6 on 2024-05-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_names_moviedetaisl'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('moviename', models.CharField(max_length=100)),
                ('heroname', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='MovieDetaisl',
        ),
    ]
